importScripts(
  "./sw/constants.js",
  "./sw/state.js",
  "./sw/init.js",
  "./sw/utils.js",
  "./sw/decode.js",
  "./sw/inject.js",
  "./sw/network.js",
  "./sw/messaging.js",
  "./sw/handler.js",
);
